### ISSUE TITLE
Add options to specify custom acoustic model and dictionary in Sphinx ASR plugin

### ISSUE THREAD

**Issue by bryandeng** [plison/opendial#11]
> The plugin requires one parameter:
> - "grammar" is the path to the recognition grammar in JSGF format

I think it's also a good idea to provide parameters for acoustic model and dictionary (maybe also via domain specification), instead of hard-coding these variables in `SphinxASR.java`.
(For example, in our project we need to use multiple models and dictionaries and switch between them. )

**Comment by plison** [comment]
OK, I've now updated the Sphinx plugin in order to use the acoustic model and dictionary as parameters. I've also added the possibility of using a statistical language model instead of a grammar. So now the plugin takes three parameters instead of one: (1) the path to the acoustic model, (2) the path to the dictionary file, and (3) the path to the grammar file *or* the path to the language model file.

Let me know if that works for you!

**Comment by bryandeng** [comment]
@plison Thanks!
